#!/bin/bash

[ -f ${XDG_CONFIG_HOME:-.config}/env.sh ] && source ${XDG_CONFIG_HOME:-.config}/env.sh

namelist=()
binlist=()
flaglist=()


if command -v sway > /dev/null; then
  namelist+=(Sway)
  binlist+=('run-sway')
  flaglist+=(C)
fi

namelist+=(Console)
binlist+=("$SHELL -li")
flaglist+=(C)


dialogrc=/usr/share/cdm/themes/blackandwhite
